apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false # don't push to docker hub
  artifacts:
    - image: chakhmah/auth
      context: auth # folder than contains code for this image
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: . # where to sync this file to in the container
