apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongo
  template:
    metadata:
      labels:
        app: orders-mongo # label applied to the pod
    spec:
      containers:
        - name: orders-mongo
          image: mongo # image comes from docker hub
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv
spec:
  selector: # tell service which pods to send traffic to
    app: orders-mongo
  ports:
    - name: db # name only for logging purposes
      protocol: TCP
      port: 27017 # port exposed by the pod (default port for mongo)
      targetPort: 27017 # port exposed by the container
